# Project: ACLLib_test
# Makefile created by Dev-C++ 5.16

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ACLLib_test/main.o ACLLib_test/acllib.o ACLLib_test/Point.o
LINKOBJ  = ACLLib_test/main.o ACLLib_test/acllib.o ACLLib_test/Point.o
LIBS     = -L"D:/DevCPP/Dev-Cpp/MinGW64/lib" -L"D:/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows  ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libwinmm.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmsimg32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libkernel32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuser32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libgdi32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libole32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/liboleaut32.a ../../../../../../Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuuid.a -m64 -g3
INCS     = -I"D:/DevCPP/Dev-Cpp/MinGW64/include" -I"D:/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include"
CXXINCS  = -I"D:/DevCPP/Dev-Cpp/MinGW64/include" -I"D:/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"D:/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++"
BIN      = ACLLib_test.exe
CXXFLAGS = $(CXXINCS) -m64 -g3
CFLAGS   = $(INCS) -m64 -g3
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ACLLib_test/main.o: ACLLib_test/main.c
	$(CC) -c ACLLib_test/main.c -o ACLLib_test/main.o $(CFLAGS)

ACLLib_test/acllib.o: ACLLib_test/acllib.c
	$(CC) -c ACLLib_test/acllib.c -o ACLLib_test/acllib.o $(CFLAGS)

ACLLib_test/Point.o: ACLLib_test/Point.c
	$(CC) -c ACLLib_test/Point.c -o ACLLib_test/Point.o $(CFLAGS)
